// This file was GENERATED by command:
//     pump.py dtest-matcher-multi-generated.h.pump
// DO NOT EDIT BY HAND!!!

//==============================================================================
/**
 * @file    dtest/dtest-matcher-multi-generated.h
 *
 * @brief   header of Dtest multi-value matchers automatically generated
 *
 * @author  ymoch
 * @date    2014/11/01
 */
//==============================================================================
#ifndef INCLUDE_DTEST_DTEST_MATCHER_MULTI_GENERATED_H
#define INCLUDE_DTEST_DTEST_MATCHER_MULTI_GENERATED_H

#include "internal/dtest-combiners.h"

namespace dtest {

//==============================================================================
/**
 * @brief   variadic matcher (N = 1)
 */
//==============================================================================
template <class Combiner, class T1>
class VariadicMatcher1
{
public:
    /**
     * @brief       constructor
     */
    VariadicMatcher1(const T1& matcher)
        : matcher_(matcher) {}

    /**
     * @brief       check that it matches
     *
     * @tparam      ValueType       value type
     * @param[in]   value           value to Matches
     * @retval      true            it matches
     * @retval      false           it doesn't match
     */
    template <class ValueType>
    bool Matches(const ValueType& value) const
    {
        return matcher_.Matches(value);
    }

    /**
     * @brief       describe self
     *
     * @param       os      output stream to describe to
     */
    void DescribeTo(::std::ostream* os) const
    {
        *os << "(" << matcher_ << ")";
    }

private:
    T1 matcher_;    //!< matcher
};
//==============================================================================
/**
 * @brief   variadic matcher (N = 2)
 */
//==============================================================================
template <class Combiner, class T1, class T2>
class VariadicMatcher2
{
public:
    /**
     * @brief       constructor
     */
    VariadicMatcher2(const T1& m1, const T2& m2)
        : head_matcher_(m1), tail_matchers_(m2) {}

    /**
     * @brief       check that it matches
     *
     * @tparam      ValueType       value type
     * @param[in]   value           value to Matches
     * @retval      true            it matches
     * @retval      false           it doesn't match
     */
    template <class ValueType>
    bool Matches(const ValueType& value) const
    {
        return Combiner::Combine(
                    head_matcher_.Matches(value),
                    tail_matchers_.Matches(value));
    }

    /**
     * @brief       describe self
     *
     * @param       os      output stream to describe to
     */
    void DescribeTo(::std::ostream* os) const
    {
        *os << "(" << head_matcher_ << ") "
            << Combiner::GetOperatorString() << " "
            << tail_matchers_;
    }

private:
    /**
     * @brief       head matcher
     */
    T1 head_matcher_;

    /**
     * @brief       tail matchers
     */
    VariadicMatcher1<Combiner, T2> tail_matchers_;
};

//==============================================================================
/**
 * @brief   variadic matcher (N = 3)
 */
//==============================================================================
template <class Combiner, class T1, class T2, class T3>
class VariadicMatcher3
{
public:
    /**
     * @brief       constructor
     */
    VariadicMatcher3(const T1& m1, const T2& m2, const T3& m3)
        : head_matcher_(m1), tail_matchers_(m2, m3) {}

    /**
     * @brief       check that it matches
     *
     * @tparam      ValueType       value type
     * @param[in]   value           value to Matches
     * @retval      true            it matches
     * @retval      false           it doesn't match
     */
    template <class ValueType>
    bool Matches(const ValueType& value) const
    {
        return Combiner::Combine(
                    head_matcher_.Matches(value),
                    tail_matchers_.Matches(value));
    }

    /**
     * @brief       describe self
     *
     * @param       os      output stream to describe to
     */
    void DescribeTo(::std::ostream* os) const
    {
        *os << "(" << head_matcher_ << ") "
            << Combiner::GetOperatorString() << " "
            << tail_matchers_;
    }

private:
    /**
     * @brief       head matcher
     */
    T1 head_matcher_;

    /**
     * @brief       tail matchers
     */
    VariadicMatcher2<Combiner, T2, T3> tail_matchers_;
};

//==============================================================================
/**
 * @brief   variadic matcher (N = 4)
 */
//==============================================================================
template <class Combiner, class T1, class T2, class T3, class T4>
class VariadicMatcher4
{
public:
    /**
     * @brief       constructor
     */
    VariadicMatcher4(const T1& m1, const T2& m2, const T3& m3, const T4& m4)
        : head_matcher_(m1), tail_matchers_(m2, m3, m4) {}

    /**
     * @brief       check that it matches
     *
     * @tparam      ValueType       value type
     * @param[in]   value           value to Matches
     * @retval      true            it matches
     * @retval      false           it doesn't match
     */
    template <class ValueType>
    bool Matches(const ValueType& value) const
    {
        return Combiner::Combine(
                    head_matcher_.Matches(value),
                    tail_matchers_.Matches(value));
    }

    /**
     * @brief       describe self
     *
     * @param       os      output stream to describe to
     */
    void DescribeTo(::std::ostream* os) const
    {
        *os << "(" << head_matcher_ << ") "
            << Combiner::GetOperatorString() << " "
            << tail_matchers_;
    }

private:
    /**
     * @brief       head matcher
     */
    T1 head_matcher_;

    /**
     * @brief       tail matchers
     */
    VariadicMatcher3<Combiner, T2, T3, T4> tail_matchers_;
};

//==============================================================================
/**
 * @brief   variadic matcher (N = 5)
 */
//==============================================================================
template <class Combiner, class T1, class T2, class T3, class T4, class T5>
class VariadicMatcher5
{
public:
    /**
     * @brief       constructor
     */
    VariadicMatcher5(const T1& m1, const T2& m2, const T3& m3, const T4& m4,
        const T5& m5)
        : head_matcher_(m1), tail_matchers_(m2, m3, m4, m5) {}

    /**
     * @brief       check that it matches
     *
     * @tparam      ValueType       value type
     * @param[in]   value           value to Matches
     * @retval      true            it matches
     * @retval      false           it doesn't match
     */
    template <class ValueType>
    bool Matches(const ValueType& value) const
    {
        return Combiner::Combine(
                    head_matcher_.Matches(value),
                    tail_matchers_.Matches(value));
    }

    /**
     * @brief       describe self
     *
     * @param       os      output stream to describe to
     */
    void DescribeTo(::std::ostream* os) const
    {
        *os << "(" << head_matcher_ << ") "
            << Combiner::GetOperatorString() << " "
            << tail_matchers_;
    }

private:
    /**
     * @brief       head matcher
     */
    T1 head_matcher_;

    /**
     * @brief       tail matchers
     */
    VariadicMatcher4<Combiner, T2, T3, T4, T5> tail_matchers_;
};

//==============================================================================
/**
 * @brief   variadic matcher (N = 6)
 */
//==============================================================================
template <class Combiner, class T1, class T2, class T3, class T4, class T5,
    class T6>
class VariadicMatcher6
{
public:
    /**
     * @brief       constructor
     */
    VariadicMatcher6(const T1& m1, const T2& m2, const T3& m3, const T4& m4,
        const T5& m5, const T6& m6)
        : head_matcher_(m1), tail_matchers_(m2, m3, m4, m5, m6) {}

    /**
     * @brief       check that it matches
     *
     * @tparam      ValueType       value type
     * @param[in]   value           value to Matches
     * @retval      true            it matches
     * @retval      false           it doesn't match
     */
    template <class ValueType>
    bool Matches(const ValueType& value) const
    {
        return Combiner::Combine(
                    head_matcher_.Matches(value),
                    tail_matchers_.Matches(value));
    }

    /**
     * @brief       describe self
     *
     * @param       os      output stream to describe to
     */
    void DescribeTo(::std::ostream* os) const
    {
        *os << "(" << head_matcher_ << ") "
            << Combiner::GetOperatorString() << " "
            << tail_matchers_;
    }

private:
    /**
     * @brief       head matcher
     */
    T1 head_matcher_;

    /**
     * @brief       tail matchers
     */
    VariadicMatcher5<Combiner, T2, T3, T4, T5, T6> tail_matchers_;
};

//==============================================================================
/**
 * @brief   variadic matcher (N = 7)
 */
//==============================================================================
template <class Combiner, class T1, class T2, class T3, class T4, class T5,
    class T6, class T7>
class VariadicMatcher7
{
public:
    /**
     * @brief       constructor
     */
    VariadicMatcher7(const T1& m1, const T2& m2, const T3& m3, const T4& m4,
        const T5& m5, const T6& m6, const T7& m7)
        : head_matcher_(m1), tail_matchers_(m2, m3, m4, m5, m6, m7) {}

    /**
     * @brief       check that it matches
     *
     * @tparam      ValueType       value type
     * @param[in]   value           value to Matches
     * @retval      true            it matches
     * @retval      false           it doesn't match
     */
    template <class ValueType>
    bool Matches(const ValueType& value) const
    {
        return Combiner::Combine(
                    head_matcher_.Matches(value),
                    tail_matchers_.Matches(value));
    }

    /**
     * @brief       describe self
     *
     * @param       os      output stream to describe to
     */
    void DescribeTo(::std::ostream* os) const
    {
        *os << "(" << head_matcher_ << ") "
            << Combiner::GetOperatorString() << " "
            << tail_matchers_;
    }

private:
    /**
     * @brief       head matcher
     */
    T1 head_matcher_;

    /**
     * @brief       tail matchers
     */
    VariadicMatcher6<Combiner, T2, T3, T4, T5, T6, T7> tail_matchers_;
};

//==============================================================================
/**
 * @brief   variadic matcher (N = 8)
 */
//==============================================================================
template <class Combiner, class T1, class T2, class T3, class T4, class T5,
    class T6, class T7, class T8>
class VariadicMatcher8
{
public:
    /**
     * @brief       constructor
     */
    VariadicMatcher8(const T1& m1, const T2& m2, const T3& m3, const T4& m4,
        const T5& m5, const T6& m6, const T7& m7, const T8& m8)
        : head_matcher_(m1), tail_matchers_(m2, m3, m4, m5, m6, m7, m8) {}

    /**
     * @brief       check that it matches
     *
     * @tparam      ValueType       value type
     * @param[in]   value           value to Matches
     * @retval      true            it matches
     * @retval      false           it doesn't match
     */
    template <class ValueType>
    bool Matches(const ValueType& value) const
    {
        return Combiner::Combine(
                    head_matcher_.Matches(value),
                    tail_matchers_.Matches(value));
    }

    /**
     * @brief       describe self
     *
     * @param       os      output stream to describe to
     */
    void DescribeTo(::std::ostream* os) const
    {
        *os << "(" << head_matcher_ << ") "
            << Combiner::GetOperatorString() << " "
            << tail_matchers_;
    }

private:
    /**
     * @brief       head matcher
     */
    T1 head_matcher_;

    /**
     * @brief       tail matchers
     */
    VariadicMatcher7<Combiner, T2, T3, T4, T5, T6, T7, T8> tail_matchers_;
};

//==============================================================================
/**
 * @brief   variadic matcher (N = 9)
 */
//==============================================================================
template <class Combiner, class T1, class T2, class T3, class T4, class T5,
    class T6, class T7, class T8, class T9>
class VariadicMatcher9
{
public:
    /**
     * @brief       constructor
     */
    VariadicMatcher9(const T1& m1, const T2& m2, const T3& m3, const T4& m4,
        const T5& m5, const T6& m6, const T7& m7, const T8& m8, const T9& m9)
        : head_matcher_(m1), tail_matchers_(m2, m3, m4, m5, m6, m7, m8, m9) {}

    /**
     * @brief       check that it matches
     *
     * @tparam      ValueType       value type
     * @param[in]   value           value to Matches
     * @retval      true            it matches
     * @retval      false           it doesn't match
     */
    template <class ValueType>
    bool Matches(const ValueType& value) const
    {
        return Combiner::Combine(
                    head_matcher_.Matches(value),
                    tail_matchers_.Matches(value));
    }

    /**
     * @brief       describe self
     *
     * @param       os      output stream to describe to
     */
    void DescribeTo(::std::ostream* os) const
    {
        *os << "(" << head_matcher_ << ") "
            << Combiner::GetOperatorString() << " "
            << tail_matchers_;
    }

private:
    /**
     * @brief       head matcher
     */
    T1 head_matcher_;

    /**
     * @brief       tail matchers
     */
    VariadicMatcher8<Combiner, T2, T3, T4, T5, T6, T7, T8, T9> tail_matchers_;
};

//==============================================================================
/**
 * @brief   variadic matcher (N = 10)
 */
//==============================================================================
template <class Combiner, class T1, class T2, class T3, class T4, class T5,
    class T6, class T7, class T8, class T9, class T10>
class VariadicMatcher10
{
public:
    /**
     * @brief       constructor
     */
    VariadicMatcher10(const T1& m1, const T2& m2, const T3& m3, const T4& m4,
        const T5& m5, const T6& m6, const T7& m7, const T8& m8, const T9& m9,
        const T10& m10)
        : head_matcher_(m1), tail_matchers_(m2, m3, m4, m5, m6, m7, m8, m9,
            m10) {}

    /**
     * @brief       check that it matches
     *
     * @tparam      ValueType       value type
     * @param[in]   value           value to Matches
     * @retval      true            it matches
     * @retval      false           it doesn't match
     */
    template <class ValueType>
    bool Matches(const ValueType& value) const
    {
        return Combiner::Combine(
                    head_matcher_.Matches(value),
                    tail_matchers_.Matches(value));
    }

    /**
     * @brief       describe self
     *
     * @param       os      output stream to describe to
     */
    void DescribeTo(::std::ostream* os) const
    {
        *os << "(" << head_matcher_ << ") "
            << Combiner::GetOperatorString() << " "
            << tail_matchers_;
    }

private:
    /**
     * @brief       head matcher
     */
    T1 head_matcher_;

    /**
     * @brief       tail matchers
     */
    VariadicMatcher9<Combiner, T2, T3, T4, T5, T6, T7, T8, T9,
        T10> tail_matchers_;
};

//==============================================================================
// definition of inline function
//==============================================================================
/**
 * @brief           operator << for VariadicMatcher1
 *
 * @param[in,out]   os          output stream
 * @param[in]       matcher     matcher
 */
template <class Combiner, class T1>
inline ::std::ostream& operator<<(::std::ostream& os,
    const VariadicMatcher1<Combiner, T1>& matcher)
{
    matcher.DescribeTo(&os);
    return os;
}

/**
 * @brief           operator << for VariadicMatcher2
 *
 * @param[in,out]   os          output stream
 * @param[in]       matcher     matcher
 */
template <class Combiner, class T1, class T2>
inline ::std::ostream& operator<<(::std::ostream& os,
    const VariadicMatcher2<Combiner, T1, T2>& matcher)
{
    matcher.DescribeTo(&os);
    return os;
}

/**
 * @brief           operator << for VariadicMatcher3
 *
 * @param[in,out]   os          output stream
 * @param[in]       matcher     matcher
 */
template <class Combiner, class T1, class T2, class T3>
inline ::std::ostream& operator<<(::std::ostream& os,
    const VariadicMatcher3<Combiner, T1, T2, T3>& matcher)
{
    matcher.DescribeTo(&os);
    return os;
}

/**
 * @brief           operator << for VariadicMatcher4
 *
 * @param[in,out]   os          output stream
 * @param[in]       matcher     matcher
 */
template <class Combiner, class T1, class T2, class T3, class T4>
inline ::std::ostream& operator<<(::std::ostream& os,
    const VariadicMatcher4<Combiner, T1, T2, T3, T4>& matcher)
{
    matcher.DescribeTo(&os);
    return os;
}

/**
 * @brief           operator << for VariadicMatcher5
 *
 * @param[in,out]   os          output stream
 * @param[in]       matcher     matcher
 */
template <class Combiner, class T1, class T2, class T3, class T4, class T5>
inline ::std::ostream& operator<<(::std::ostream& os,
    const VariadicMatcher5<Combiner, T1, T2, T3, T4, T5>& matcher)
{
    matcher.DescribeTo(&os);
    return os;
}

/**
 * @brief           operator << for VariadicMatcher6
 *
 * @param[in,out]   os          output stream
 * @param[in]       matcher     matcher
 */
template <class Combiner, class T1, class T2, class T3, class T4, class T5,
    class T6>
inline ::std::ostream& operator<<(::std::ostream& os,
    const VariadicMatcher6<Combiner, T1, T2, T3, T4, T5, T6>& matcher)
{
    matcher.DescribeTo(&os);
    return os;
}

/**
 * @brief           operator << for VariadicMatcher7
 *
 * @param[in,out]   os          output stream
 * @param[in]       matcher     matcher
 */
template <class Combiner, class T1, class T2, class T3, class T4, class T5,
    class T6, class T7>
inline ::std::ostream& operator<<(::std::ostream& os,
    const VariadicMatcher7<Combiner, T1, T2, T3, T4, T5, T6, T7>& matcher)
{
    matcher.DescribeTo(&os);
    return os;
}

/**
 * @brief           operator << for VariadicMatcher8
 *
 * @param[in,out]   os          output stream
 * @param[in]       matcher     matcher
 */
template <class Combiner, class T1, class T2, class T3, class T4, class T5,
    class T6, class T7, class T8>
inline ::std::ostream& operator<<(::std::ostream& os,
    const VariadicMatcher8<Combiner, T1, T2, T3, T4, T5, T6, T7, T8>& matcher)
{
    matcher.DescribeTo(&os);
    return os;
}

/**
 * @brief           operator << for VariadicMatcher9
 *
 * @param[in,out]   os          output stream
 * @param[in]       matcher     matcher
 */
template <class Combiner, class T1, class T2, class T3, class T4, class T5,
    class T6, class T7, class T8, class T9>
inline ::std::ostream& operator<<(::std::ostream& os,
    const VariadicMatcher9<Combiner, T1, T2, T3, T4, T5, T6, T7, T8,
    T9>& matcher)
{
    matcher.DescribeTo(&os);
    return os;
}

/**
 * @brief           operator << for VariadicMatcher10
 *
 * @param[in,out]   os          output stream
 * @param[in]       matcher     matcher
 */
template <class Combiner, class T1, class T2, class T3, class T4, class T5,
    class T6, class T7, class T8, class T9, class T10>
inline ::std::ostream& operator<<(::std::ostream& os,
    const VariadicMatcher10<Combiner, T1, T2, T3, T4, T5, T6, T7, T8, T9,
    T10>& matcher)
{
    matcher.DescribeTo(&os);
    return os;
}

/**
 * @brief       create AND matcher
 *
 * @return      matcher
 */
template <class T1>
inline VariadicMatcher1<AndCombiner, T1> AllOf(const T1& m1)
{
    return VariadicMatcher1<AndCombiner, T1>(m1);
}

/**
 * @brief       create AND matcher
 *
 * @return      matcher
 */
template <class T1, class T2>
inline VariadicMatcher2<AndCombiner, T1, T2> AllOf(const T1& m1, const T2& m2)
{
    return VariadicMatcher2<AndCombiner, T1, T2>(m1, m2);
}

/**
 * @brief       create AND matcher
 *
 * @return      matcher
 */
template <class T1, class T2, class T3>
inline VariadicMatcher3<AndCombiner, T1, T2, T3> AllOf(const T1& m1,
    const T2& m2, const T3& m3)
{
    return VariadicMatcher3<AndCombiner, T1, T2, T3>(m1, m2, m3);
}

/**
 * @brief       create AND matcher
 *
 * @return      matcher
 */
template <class T1, class T2, class T3, class T4>
inline VariadicMatcher4<AndCombiner, T1, T2, T3, T4> AllOf(const T1& m1,
    const T2& m2, const T3& m3, const T4& m4)
{
    return VariadicMatcher4<AndCombiner, T1, T2, T3, T4>(m1, m2, m3, m4);
}

/**
 * @brief       create AND matcher
 *
 * @return      matcher
 */
template <class T1, class T2, class T3, class T4, class T5>
inline VariadicMatcher5<AndCombiner, T1, T2, T3, T4, T5> AllOf(const T1& m1,
    const T2& m2, const T3& m3, const T4& m4, const T5& m5)
{
    return VariadicMatcher5<AndCombiner, T1, T2, T3, T4, T5>(m1, m2, m3, m4,
        m5);
}

/**
 * @brief       create AND matcher
 *
 * @return      matcher
 */
template <class T1, class T2, class T3, class T4, class T5, class T6>
inline VariadicMatcher6<AndCombiner, T1, T2, T3, T4, T5,
    T6> AllOf(const T1& m1, const T2& m2, const T3& m3, const T4& m4,
    const T5& m5, const T6& m6)
{
    return VariadicMatcher6<AndCombiner, T1, T2, T3, T4, T5, T6>(m1, m2, m3,
        m4, m5, m6);
}

/**
 * @brief       create AND matcher
 *
 * @return      matcher
 */
template <class T1, class T2, class T3, class T4, class T5, class T6, class T7>
inline VariadicMatcher7<AndCombiner, T1, T2, T3, T4, T5, T6,
    T7> AllOf(const T1& m1, const T2& m2, const T3& m3, const T4& m4,
    const T5& m5, const T6& m6, const T7& m7)
{
    return VariadicMatcher7<AndCombiner, T1, T2, T3, T4, T5, T6, T7>(m1, m2,
        m3, m4, m5, m6, m7);
}

/**
 * @brief       create AND matcher
 *
 * @return      matcher
 */
template <class T1, class T2, class T3, class T4, class T5, class T6, class T7,
    class T8>
inline VariadicMatcher8<AndCombiner, T1, T2, T3, T4, T5, T6, T7,
    T8> AllOf(const T1& m1, const T2& m2, const T3& m3, const T4& m4,
    const T5& m5, const T6& m6, const T7& m7, const T8& m8)
{
    return VariadicMatcher8<AndCombiner, T1, T2, T3, T4, T5, T6, T7, T8>(m1,
        m2, m3, m4, m5, m6, m7, m8);
}

/**
 * @brief       create AND matcher
 *
 * @return      matcher
 */
template <class T1, class T2, class T3, class T4, class T5, class T6, class T7,
    class T8, class T9>
inline VariadicMatcher9<AndCombiner, T1, T2, T3, T4, T5, T6, T7, T8,
    T9> AllOf(const T1& m1, const T2& m2, const T3& m3, const T4& m4,
    const T5& m5, const T6& m6, const T7& m7, const T8& m8, const T9& m9)
{
    return VariadicMatcher9<AndCombiner, T1, T2, T3, T4, T5, T6, T7, T8,
        T9>(m1, m2, m3, m4, m5, m6, m7, m8, m9);
}

/**
 * @brief       create AND matcher
 *
 * @return      matcher
 */
template <class T1, class T2, class T3, class T4, class T5, class T6, class T7,
    class T8, class T9, class T10>
inline VariadicMatcher10<AndCombiner, T1, T2, T3, T4, T5, T6, T7, T8, T9,
    T10> AllOf(const T1& m1, const T2& m2, const T3& m3, const T4& m4,
    const T5& m5, const T6& m6, const T7& m7, const T8& m8, const T9& m9,
    const T10& m10)
{
    return VariadicMatcher10<AndCombiner, T1, T2, T3, T4, T5, T6, T7, T8, T9,
        T10>(m1, m2, m3, m4, m5, m6, m7, m8, m9, m10);
}

/**
 * @brief       create OR matcher
 *
 * @return      matcher
 */
template <class T1>
inline VariadicMatcher1<OrCombiner, T1> AnyOf(const T1& m1)
{
    return VariadicMatcher1<OrCombiner, T1>(m1);
}

/**
 * @brief       create OR matcher
 *
 * @return      matcher
 */
template <class T1, class T2>
inline VariadicMatcher2<OrCombiner, T1, T2> AnyOf(const T1& m1, const T2& m2)
{
    return VariadicMatcher2<OrCombiner, T1, T2>(m1, m2);
}

/**
 * @brief       create OR matcher
 *
 * @return      matcher
 */
template <class T1, class T2, class T3>
inline VariadicMatcher3<OrCombiner, T1, T2, T3> AnyOf(const T1& m1,
    const T2& m2, const T3& m3)
{
    return VariadicMatcher3<OrCombiner, T1, T2, T3>(m1, m2, m3);
}

/**
 * @brief       create OR matcher
 *
 * @return      matcher
 */
template <class T1, class T2, class T3, class T4>
inline VariadicMatcher4<OrCombiner, T1, T2, T3, T4> AnyOf(const T1& m1,
    const T2& m2, const T3& m3, const T4& m4)
{
    return VariadicMatcher4<OrCombiner, T1, T2, T3, T4>(m1, m2, m3, m4);
}

/**
 * @brief       create OR matcher
 *
 * @return      matcher
 */
template <class T1, class T2, class T3, class T4, class T5>
inline VariadicMatcher5<OrCombiner, T1, T2, T3, T4, T5> AnyOf(const T1& m1,
    const T2& m2, const T3& m3, const T4& m4, const T5& m5)
{
    return VariadicMatcher5<OrCombiner, T1, T2, T3, T4, T5>(m1, m2, m3, m4, m5);
}

/**
 * @brief       create OR matcher
 *
 * @return      matcher
 */
template <class T1, class T2, class T3, class T4, class T5, class T6>
inline VariadicMatcher6<OrCombiner, T1, T2, T3, T4, T5, T6> AnyOf(const T1& m1,
    const T2& m2, const T3& m3, const T4& m4, const T5& m5, const T6& m6)
{
    return VariadicMatcher6<OrCombiner, T1, T2, T3, T4, T5, T6>(m1, m2, m3, m4,
        m5, m6);
}

/**
 * @brief       create OR matcher
 *
 * @return      matcher
 */
template <class T1, class T2, class T3, class T4, class T5, class T6, class T7>
inline VariadicMatcher7<OrCombiner, T1, T2, T3, T4, T5, T6,
    T7> AnyOf(const T1& m1, const T2& m2, const T3& m3, const T4& m4,
    const T5& m5, const T6& m6, const T7& m7)
{
    return VariadicMatcher7<OrCombiner, T1, T2, T3, T4, T5, T6, T7>(m1, m2, m3,
        m4, m5, m6, m7);
}

/**
 * @brief       create OR matcher
 *
 * @return      matcher
 */
template <class T1, class T2, class T3, class T4, class T5, class T6, class T7,
    class T8>
inline VariadicMatcher8<OrCombiner, T1, T2, T3, T4, T5, T6, T7,
    T8> AnyOf(const T1& m1, const T2& m2, const T3& m3, const T4& m4,
    const T5& m5, const T6& m6, const T7& m7, const T8& m8)
{
    return VariadicMatcher8<OrCombiner, T1, T2, T3, T4, T5, T6, T7, T8>(m1, m2,
        m3, m4, m5, m6, m7, m8);
}

/**
 * @brief       create OR matcher
 *
 * @return      matcher
 */
template <class T1, class T2, class T3, class T4, class T5, class T6, class T7,
    class T8, class T9>
inline VariadicMatcher9<OrCombiner, T1, T2, T3, T4, T5, T6, T7, T8,
    T9> AnyOf(const T1& m1, const T2& m2, const T3& m3, const T4& m4,
    const T5& m5, const T6& m6, const T7& m7, const T8& m8, const T9& m9)
{
    return VariadicMatcher9<OrCombiner, T1, T2, T3, T4, T5, T6, T7, T8, T9>(m1,
        m2, m3, m4, m5, m6, m7, m8, m9);
}

/**
 * @brief       create OR matcher
 *
 * @return      matcher
 */
template <class T1, class T2, class T3, class T4, class T5, class T6, class T7,
    class T8, class T9, class T10>
inline VariadicMatcher10<OrCombiner, T1, T2, T3, T4, T5, T6, T7, T8, T9,
    T10> AnyOf(const T1& m1, const T2& m2, const T3& m3, const T4& m4,
    const T5& m5, const T6& m6, const T7& m7, const T8& m8, const T9& m9,
    const T10& m10)
{
    return VariadicMatcher10<OrCombiner, T1, T2, T3, T4, T5, T6, T7, T8, T9,
        T10>(m1, m2, m3, m4, m5, m6, m7, m8, m9, m10);
}

} // namespace dtest

#endif // INCLUDE_DTEST_DTEST_MATCHER_MULTI_GENERATED_H
